#!/usr/bin/env bash
#we conect to the error page 404

sudo apt-get -y update
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/BrunoGuerraS permanent;/" /etc/nginx/sites-available/default
sudo sed -i "s/^server\s{/server {\n\terror_page 404 \/404.html;/1" /etc/nginx/sites-available/default
sudo service nginx restart
