#!/usr/bin/env bash
# basic

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/BrunoGuerraS permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
