#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# in line 4th bad luck
# in line 8th good luck
i=1
while [ $i -le 10 ]
do
        if test $i == 4
        then
                echo "bad luck"
        elif test $i == 8
	then
		echo "good luck"
	else
		echo "Best School"
	fi
        i=$(( i + 1 ))
done
