#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
minuto=1
hora=0
while [ $hora -lt 13 ]
do
	echo "Hour: $hora"
	while [ $minuto -lt 60 ]
	do
		echo "$minuto"
		minuto=$(( minuto + 1 ))
	done
	minuto=1
	hora=$(( hora + 1 ))
done
