#!/usr/bin/env bash
#create a owner
chown nginx:nginx /etc/nginx/nginx.conf
#changing permission
chmod 700 /etc/nginx/nginx.conf
#Changes port 80 to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
#restart nginx
sudo -u nginx service nginx restart
